### ISSUE TITLE
Could not load the Qt platform plugin "xcb" in "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" even though it was found.

### ISSUE THREAD

**Issue by Codechilla** [BBC-Esq/ctranslate2-faster-whisper-transcriber#1]
I'm on PopOS based on Ubuntu 22.04. Been getting the below error after running 'python ct2_main.py', no matter what solution I try. Any idea how to resolve this? Google and ChatGPT have not been helpful? Thanks in advance.

Updated cpu quantizations in config.yaml to: ['float32', 'int8_float32', 'int8']
Updated cuda quantizations in config.yaml to: ['float32', 'int8_float32', 'float16', 'int8_float16', 'int8']
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: vnc, offscreen, wayland-egl, minimalegl, linuxfb, vkkhrdisplay, wayland, minimal, eglfs, xcb.

Aborted (core dumped)

**Comment by BBC-Esq** [comment]
I've never see that message before.  I'll look into it.

**Comment by BBC-Esq** [comment]
It's hard to help without knowing which troubleshooting steps you already took.  Check this link out and let me know if it helps or maybe it's a good starting point:

https://chat.openai.com/share/bac52d7a-c110-4886-a773-d44f5ad26259

**Comment by Codechilla** [comment]
Thanks. That's basically the same thing ChatGPT told me, although some some differences, so I tried your instructions with no avail. I'm going to install a Linux distro with KDE desktop to see if the it has the same issues with Qt. I will let you know if it works.

**Comment by Codechilla** [comment]
Thanks. That's basically the same thing ChatGPT told me, although some some differences, so I tried your instructions with no avail. I'm going to install a Linux distro with KDE desktop to see if the it has the same issues with Qt. I will let you know if it works.

**Comment by Codechilla** [comment]
It worked right away on MX Linux with KDE.

**Comment by BBC-Esq** [comment]
Hmm...I'll close this out for now but feel free to post another issue if something crops up.

**Comment by Codechilla** [comment]
SOLVED: I ran ‘QT_DEBUG_PLUGINS=1 python ct2_main.py’, and fed the output into ChatGPT, who then said to run ‘sudo apt-get update’ and ‘sudo apt-get install libxcb-cursor0’ which installed a missing dependency.

**Comment by BBC-Esq** [comment]
Great, I'll make a note of it and possibly update my installation instructions!
