### ISSUE TITLE
Paste output duplicates and has inconsistencies

### ISSUE THREAD

**Issue by Codechilla** [BBC-Esq/ctranslate2-faster-whisper-transcriber#2]
Using MX Linux 23.2 the paste results seem to duplicate a random amount. See my test results below trying the medium.en, small.en, and base.en models:

 Where does sunshine come from?
 Where does sunshine come from?
 Where does sunshine come from?
 Where does sunshine come from?
 Where does sunshine come from?
 Where does sunshine come from?
 Where does sunshine come from? 
 
  Tell me about the complexities of quantum physics.
 
 Tell me about the complexities of quantum physics.
  
 Tell me where you're at right now.
 Tell me where you're at right now.
 Tell me where you're at right now.
 Tell me where you're at right now.
 Tell me where you're at right now.
 Tell me where you're at right now.
 Tell me where you're at right now.
 Tell me where you're at right now.
 Tell me where you're at right now.
 Tell me where you're at right now.
 Tell me where you're at right now.
 Tell me where you're at right now.
 
  Hello, can I help you?
 Hello, can I help you?
 Hello, can I help you?
 
 
  Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 Where do blue lights go at night?
 
 
  Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me how long it takes to get to New York City. Tell me
  
   What can we do for you today, mister?
 What can we do for you today, mister?
 What can we do for you today, mister?

**Comment by BBC-Esq** [comment]
Thank you for the bug report.  Can you reinstalled using faster-whisper0.9.0 instead of 1.0.0?  I've noticed a few issues with 1.0.0 that they're trying to still get worked out...

**Comment by BBC-Esq** [comment]
I know that the faster-whisper people are working on fixing the recent updates to version 1.0 and 0.10.0...It's been hectic.

**Comment by Codechilla** [comment]
Installing faster-whisper 0.9.0 solved the problem! Working perfectly now on PopOS. Thanks for the help.
