### ISSUE TITLE
Models don't always change after updating.

### ISSUE THREAD

**Issue by Codechilla** [BBC-Esq/ctranslate2-faster-whisper-transcriber#3]
After changing models and clicking the update button (sweet feature btw), on MX Linux 23.2 it appears to stay on the previous model, which is especially obvious when switching between medium and small or base.

Restarting the program seems to solve the problem though, so good for now.

Love the app btw.

**Comment by BBC-Esq** [comment]
Thanks for letting me know.

**Comment by BBC-Esq** [comment]
Can you try using faster-whisper 0.9.0 instead and see if the app does the same thing?

```pip3 install faster-whisper==0.9.0```

**Comment by Codechilla** [comment]
Installing faster-whisper 0.9.0 solved the problem! Working perfectly now on PopOS. Thanks for the help.

**Comment by BBC-Esq** [comment]
No problem!  Here's to hoping that they fix the bugs ASAP because I really like the library.
